
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author bayer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    ArrayList<PC> compus = new ArrayList();

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFramecrud = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        botonlaptop = new javax.swing.JButton();
        botonescritorio = new javax.swing.JButton();
        botonlistar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jFramelaptop = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        IP = new javax.swing.JTextField();
        Mascarared = new javax.swing.JTextField();
        Hostname = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Definiciondepantalla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rgb = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        botonagregarvariable = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jFrameescritorio = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IP2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Mascarared2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hostname2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        memram = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        almacenamientoo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tipodealma = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tienetarjeta = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        agregarescritorio = new javax.swing.JButton();
        jFrameListar = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        listarcompus = new javax.swing.JTextArea();
        salirlistar = new javax.swing.JButton();
        Jframeremove = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaquitar = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        cualborrar = new javax.swing.JTextField();
        botonborrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Botonagregarcompu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Botoningresarcompu = new javax.swing.JButton();

        jFramecrud.setBackground(new java.awt.Color(255, 255, 0));
        jFramecrud.setSize(new java.awt.Dimension(593, 464));
        jFramecrud.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel16.setText("En caso de agregar, ingrese cual");

        botonlaptop.setText("Laptop");
        botonlaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonlaptopMouseClicked(evt);
            }
        });
        botonlaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlaptopActionPerformed(evt);
            }
        });

        botonescritorio.setText("Escritorio");
        botonescritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonescritorioMouseClicked(evt);
            }
        });

        botonlistar.setText("Listar");
        botonlistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonlistarMouseClicked(evt);
            }
        });

        botoneliminar.setText("Eliminar de la lista");
        botoneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoneliminarMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel18.setText("ELIMINAR Y LISTAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonlaptop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(botoneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel18)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jFramecrud.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        jFramelaptop.setPreferredSize(new java.awt.Dimension(600, 550));
        jFramelaptop.setSize(new java.awt.Dimension(600, 550));
        jFramelaptop.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPActionPerformed(evt);
            }
        });

        jLabel1.setText("IP:");

        jLabel2.setText("Mascara de Red:");

        jLabel3.setText("Host Name:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Definicion de Pantalla:");

        Definiciondepantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefiniciondepantallaActionPerformed(evt);
            }
        });

        rgb.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        rgb.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Si", "No" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(rgb);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("¿El teclado tiene RGB?");

        botonagregarvariable.setText("Agregar Laptop");
        botonagregarvariable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonagregarvariableMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel7.setText("AGREGANDO UNA LAPTOP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(botonagregarvariable, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Hostname)
                                    .addComponent(marca)
                                    .addComponent(Mascarared)
                                    .addComponent(IP)
                                    .addComponent(Definiciondepantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mascarared, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hostname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marca)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Definiciondepantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonagregarvariable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );

        jFramelaptop.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        jFrameescritorio.setPreferredSize(new java.awt.Dimension(900, 600));
        jFrameescritorio.setSize(new java.awt.Dimension(900, 600));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel8.setText("AGREGANDO UNA COMPUTADORA DE ESCRITORIO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("IP:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Mascara de red:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Host Name:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Cuanto tiene de Ram:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Almacenamiento:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Tipo de Almacenamiento:");

        tienetarjeta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tienetarjeta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Si", "No" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(tienetarjeta);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("¿Tiene Tarjeta Grafica?");

        agregarescritorio.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        agregarescritorio.setText("Agregar Computadora");
        agregarescritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarescritorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IP2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Mascarared2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(hostname2))
                            .addGap(27, 27, 27)
                            .addComponent(jLabel15)
                            .addGap(105, 105, 105)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memram, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(almacenamientoo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipodealma, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(agregarescritorio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IP2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Mascarared2))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hostname2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(memram))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(almacenamientoo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipodealma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(agregarescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout jFrameescritorioLayout = new javax.swing.GroupLayout(jFrameescritorio.getContentPane());
        jFrameescritorio.getContentPane().setLayout(jFrameescritorioLayout);
        jFrameescritorioLayout.setHorizontalGroup(
            jFrameescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameescritorioLayout.setVerticalGroup(
            jFrameescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameescritorioLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrameListar.setSize(new java.awt.Dimension(601, 485));

        listarcompus.setColumns(20);
        listarcompus.setRows(5);
        jScrollPane3.setViewportView(listarcompus);

        salirlistar.setText("SALIR");
        salirlistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirlistarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFrameListarLayout = new javax.swing.GroupLayout(jFrameListar.getContentPane());
        jFrameListar.getContentPane().setLayout(jFrameListarLayout);
        jFrameListarLayout.setHorizontalGroup(
            jFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameListarLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jFrameListarLayout.setVerticalGroup(
            jFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameListarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(salirlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        Jframeremove.setSize(new java.awt.Dimension(471, 431));

        listaquitar.setColumns(20);
        listaquitar.setRows(5);
        jScrollPane5.setViewportView(listaquitar);

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel19.setText("Ingrese el numero del que quiere borrar");

        botonborrar.setText("Borrar");
        botonborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonborrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JframeremoveLayout = new javax.swing.GroupLayout(Jframeremove.getContentPane());
        Jframeremove.getContentPane().setLayout(JframeremoveLayout);
        JframeremoveLayout.setHorizontalGroup(
            JframeremoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JframeremoveLayout.createSequentialGroup()
                .addGroup(JframeremoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JframeremoveLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel19))
                    .addGroup(JframeremoveLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(cualborrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JframeremoveLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(botonborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JframeremoveLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        JframeremoveLayout.setVerticalGroup(
            JframeremoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JframeremoveLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cualborrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Botonagregarcompu.setText("CRUD");
        Botonagregarcompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonagregarcompuMouseClicked(evt);
            }
        });
        Botonagregarcompu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonagregarcompuActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel17.setText("Que quiere hacer?");

        Botoningresarcompu.setText("Ingresar a computadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botoningresarcompu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Botonagregarcompu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Botonagregarcompu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Botoningresarcompu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonagregarcompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonagregarcompuMouseClicked
        jFramecrud.setVisible(true);
        jFramecrud.setLocationRelativeTo(null);
    }//GEN-LAST:event_BotonagregarcompuMouseClicked

    private void botonlaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonlaptopActionPerformed

    private void BotonagregarcompuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonagregarcompuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonagregarcompuActionPerformed

    private void botonlaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlaptopMouseClicked
        jFramelaptop.setVisible(true);
        jFramelaptop.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonlaptopMouseClicked

    private void botonescritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonescritorioMouseClicked
        jFrameescritorio.setVisible(true);
        jFrameescritorio.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonescritorioMouseClicked

    private void IPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPActionPerformed

    private void botonagregarvariableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonagregarvariableMouseClicked
        if (IP.getText().isBlank() || Mascarared.getText().isBlank() || Hostname.getText().isBlank() || marca.getText().isBlank() || Definiciondepantalla.getText().isBlank() || rgb.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede dejar NI UN solo espacio en blanco");
        } else {
            boolean serargb;
            if (rgb.getSelectedValue().equalsIgnoreCase("si")) {
                serargb = true;
            } else {
                serargb = false;
            }
            compus.add(new PC_Laptop(marca.getText(), Definiciondepantalla.getText(), serargb, IP.getText(), Mascarared.getText(), Hostname.getText()));
            JOptionPane.showMessageDialog(null, "Se agrego una nueva laptop");
            IP.setText("");
            Mascarared.setText("");
            Hostname.setText("");
            marca.setText("");
            Definiciondepantalla.setText("");
            rgb.setSelectedValue(null, false);
            jFramelaptop.setVisible(false);
        }
    }//GEN-LAST:event_botonagregarvariableMouseClicked

    private void DefiniciondepantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefiniciondepantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefiniciondepantallaActionPerformed

    private void agregarescritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarescritorioMouseClicked
        if (IP2.getText().isBlank() || Mascarared2.getText().isBlank() || hostname2.getText().isBlank() || memram.getText().isBlank() || almacenamientoo.getText().isBlank() || tipodealma.getText().isBlank() || tienetarjeta.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede dejar NI UN solo espacio en blanco");
        } else {
            boolean tendra;
            if (tienetarjeta.getSelectedValue().equalsIgnoreCase("Si")) {
                tendra = true;
            } else {
                tendra = false;
            }
            int memoriaram = Integer.parseInt(memram.getText());
            int alma = Integer.parseInt(almacenamientoo.getText());
            compus.add(new PC_Escritorio(memoriaram, alma, tipodealma.getText(), tendra, IP2.getText(), Mascarared2.getText(), hostname2.getText()));
            JOptionPane.showMessageDialog(null, "Se agrego una nueva computadora de escritorio");
            IP2.setText("");
            Mascarared2.setText("");
            hostname2.setText("");
            memram.setText("");
            almacenamientoo.setText("");
            tipodealma.setText("");
            tienetarjeta.setSelectedValue(null, false);
            jFrameescritorio.setVisible(false);
        }
    }//GEN-LAST:event_agregarescritorioMouseClicked

    private void botonlistarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlistarMouseClicked
        jFrameListar.setVisible(true);
        listarcompus.setText(compus.toString());

    }//GEN-LAST:event_botonlistarMouseClicked

    private void botoneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoneliminarMouseClicked
        Jframeremove.setVisible(true);
        String s = "";
        for (int i = 0; i < compus.size(); i++) {
            s+= compus.indexOf(i)+"- "+compus.toString()+"\n";
        }
        listaquitar.setText(s);
    }//GEN-LAST:event_botoneliminarMouseClicked

    private void salirlistarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirlistarMouseClicked
        jFrameListar.setVisible(false);
    }//GEN-LAST:event_salirlistarMouseClicked

    private void botonborrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonborrarMouseClicked
        int cual = Integer.parseInt(cualborrar.getText());
        compus.remove(cual);
        
    }//GEN-LAST:event_botonborrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonagregarcompu;
    private javax.swing.JButton Botoningresarcompu;
    private javax.swing.JTextField Definiciondepantalla;
    private javax.swing.JTextField Hostname;
    private javax.swing.JTextField IP;
    private javax.swing.JTextField IP2;
    private javax.swing.JFrame Jframeremove;
    private javax.swing.JTextField Mascarared;
    private javax.swing.JTextField Mascarared2;
    private javax.swing.JButton agregarescritorio;
    private javax.swing.JTextField almacenamientoo;
    private javax.swing.JButton botonagregarvariable;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonescritorio;
    private javax.swing.JButton botonlaptop;
    private javax.swing.JButton botonlistar;
    private javax.swing.JTextField cualborrar;
    private javax.swing.JTextField hostname2;
    private javax.swing.JFrame jFrameListar;
    private javax.swing.JFrame jFramecrud;
    private javax.swing.JFrame jFrameescritorio;
    private javax.swing.JFrame jFramelaptop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea listaquitar;
    private javax.swing.JTextArea listarcompus;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField memram;
    private javax.swing.JList<String> rgb;
    private javax.swing.JButton salirlistar;
    private javax.swing.JList<String> tienetarjeta;
    private javax.swing.JTextField tipodealma;
    // End of variables declaration//GEN-END:variables
}
